### PR TITLE
Update debug to 2.6.8 to remove ms vulnerability

### PR DESCRIPTION
**Pull request by lostthetrail**
Updating to latest ms to prevent DOS attack on `ms`.

https://github.com/visionmedia/debug/blob/master/CHANGELOG.md#267--2017-05-16

https://nodesecurity.io/advisories/46

### CODE REVIEW

**Comment by lostthetrail** [comment]
@jlai can you take a look and potentially merge/release?

**Comment by lostthetrail** [comment]
@sommestad Can you help move this along?

**Comment by lostthetrail** [comment]
@cjwilliams Or maybe you can help move this along?

**Comment by jlai** [comment]
Published 1.3.0 with your change. Thanks for the PR and sorry for the delay.

**Comment by lostthetrail** [comment]
@jlai Thanks so much!

**Pull request merged**
